apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-centos
spec:
  replicas: 1
  selector:
    role: centos01
  template:
    metadata:
      labels:
        role: centos01
    spec:
      containers:
      - name: centos-nfs01
        image: zach_centos:7.0
        ports:
          - name: ssh
            containerPort: 22
        volumeMounts:
            # name must match the volume name below
            - name: nfs
              mountPath: "/mnt"
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
