apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-redis
spec:
  replicas: 2
  selector:
    role: redis01
  template:
    metadata:
      labels:
        role: redis01
    spec:
      containers:
      - name: redis-nfs01
        image: redis
        ports:
          - name: redis
            containerPort: 11211
        volumeMounts:
            # name must match the volume name below
            - name: nfs
              mountPath: "/mnt"
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
