apiVersion: v1
kind: Pod
metadata:
  name: zachredis2
spec:
  containers:
  - name: zachredis2
    image: redis
    volumeMounts:
    - name: redis-persistent-storage
      mountPath: /data/redis
  volumes:
  - name: redis-persistent-storage
    hostPath:
      path: /zachstorge
